/* 为了防止任何可能出现的数据丢失问题，您应该先仔细检查此脚本，然后再在数据库设计器的上下文之外运行此脚本。*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.T_PAYER
	(
	id int NOT NULL IDENTITY (1, 1),
	linkman_name nvarchar(100) NULL,
	linkman_mobile nvarchar(50) NULL,
	credit_id int NULL,
	status int NULL,
	create_by int NULL,
	create_date date NULL,
	modify_by int NULL,
	modify_date date NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.T_PAYER ADD CONSTRAINT
	PK_T_PAYER PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.T_PAYER SET (LOCK_ESCALATION = TABLE)
GO
COMMIT