CREATE TABLE [dbo].[T_RENT_FILEDETAIL_LOG] (
[ID] int NOT NULL IDENTITY(1,1),
[REFD_ID] int NULL,
[IS_ALREADY] int NULL,
[IS_ALREADY_DETAIL] int null,
[ISSURE_REASON] varchar(1000) COLLATE Chinese_PRC_CI_AS NULL,
[FILE_MEMO] varchar(5000) COLLATE Chinese_PRC_CI_AS NULL,
[SALES_CREATE_ID] int NULL,
[SALES_CREATE_TIME] datetime NULL,
[confirm_date] date NULL,
[RETURN_DATE] date NULL,
PRIMARY KEY CLUSTERED ([ID] )
);

ALTER TABLE [T_RENT_FILEDETAIL]
ADD [IS_ALREADY_DETAIL] int null;