UPDATE [T_RENT_FILEDETAIL] SET IS_ALREADY = 0,IS_ALREADY_DETAIL=0
WHERE IS_ALREADY IS null;

UPDATE [T_RENT_FILEDETAIL_LOG] SET IS_ALREADY = 0,IS_ALREADY_DETAIL=0
WHERE IS_ALREADY IS null;

UPDATE [T_RENT_FILEDETAIL] SET IS_ALREADY_DETAIL = IS_ALREADY
WHERE IS_ALREADY IN(0,1);

UPDATE [T_RENT_FILEDETAIL_LOG] SET IS_ALREADY_DETAIL = IS_ALREADY
WHERE IS_ALREADY IN(0,1);

UPDATE [T_RENT_FILEDETAIL] SET IS_ALREADY_DETAIL = IS_ALREADY,IS_ALREADY = (CASE WHEN IS_ALREADY IN(2) THEN 1 ELSE 0 END)
WHERE IS_ALREADY NOT IN(0,1);

UPDATE [T_RENT_FILEDETAIL_LOG] SET IS_ALREADY_DETAIL = IS_ALREADY,IS_ALREADY = (CASE WHEN IS_ALREADY IN(2) THEN 1 ELSE 0 END)
WHERE IS_ALREADY NOT IN(0,1);